using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace Module.AnimationUtility.Editor.AnimatorParamGenerator
{
    public static class GenerationLogic
    {
        internal static void GenerateForGroup(AnimatorControllerBindingGeneratorSetting settings)
        {
            if (settings.settingGroupList == null)
            {
                Debug.LogWarning("AnimatorParamGenerator: Setting group list is not set.");
                return;
            }
            var outputPath = settings.outputFolder;

            foreach (var settingGroup in settings.settingGroupList)
            {
                if (string.IsNullOrEmpty(outputPath) || string.IsNullOrEmpty(settingGroup.className)) continue;

                var directory = Path.GetDirectoryName(outputPath);
                if (directory != null && !Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                var filePath = $"{outputPath}/{settingGroup.className}.cs";
                var controller = settingGroup.controller;

                if (controller == null)
                {
                    Debug.LogWarning(
                        $"AnimatorParamGenerator: AnimatorController is not set for {settingGroup.className}.");
                    continue;
                }

                var sb = GenerateCode(settingGroup, settings.namespaceName);

                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
                AssetDatabase.ImportAsset(filePath);
                Debug.Log($"AnimatorParamGenerator: Regenerated {filePath}.");
            }
        }

        private static StringBuilder GenerateCode(AnimatorSettingGroup settingGroup, string namespaceName)
        {
            var controller = settingGroup.controller;
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AnimatorBindingGenerator");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            var indent = 0;
            if (!string.IsNullOrWhiteSpace(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
                indent = 1;
            }

            sb.AppendLine(Ind(indent) + $"public static class {settingGroup.className}");
            sb.AppendLine(Ind(indent) + "{");

            WriteParameterConstants(sb, controller.parameters, indent + 1);
            WriteStateConstants(sb, controller, indent + 1);

            sb.AppendLine(Ind(indent) + "}");

            if (!string.IsNullOrWhiteSpace(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb;
        }

        private static void WriteParameterConstants(StringBuilder sb, AnimatorControllerParameter[] parameters,
            int indent)
        {
            if (parameters.Length == 0)
            {
                sb.AppendLine(Ind(indent) + "// No parameters found in the controller.");
                return;
            }

            // Generate Enum
            sb.AppendLine(Ind(indent) + "public enum Parameter");
            sb.AppendLine(Ind(indent) + "{");
            foreach (var p in parameters)
            {
                sb.AppendLine(Ind(indent + 1) + $"{p.name.Replace(" ", "_")},");
            }

            sb.AppendLine(Ind(indent) + "}");
            sb.AppendLine();

            // Generate Dictionary
            sb.AppendLine(Ind(indent) +
                          "private static readonly Dictionary<Parameter, int> ParameterHashes = new Dictionary<Parameter, int>");
            sb.AppendLine(Ind(indent) + "{");
            foreach (var p in parameters)
            {
                sb.AppendLine(Ind(indent + 1) +
                              $"{{ Parameter.{p.name.Replace(" ", "_")}, Animator.StringToHash(\"{p.name}\") }},");
            }

            sb.AppendLine(Ind(indent) + "};");
            sb.AppendLine();

            // Generate ToHash method
            sb.AppendLine(Ind(indent) + "public static int ToHash(this Parameter parameter)");
            sb.AppendLine(Ind(indent) + "{");
            sb.AppendLine(Ind(indent + 1) + "return ParameterHashes[parameter];");
            sb.AppendLine(Ind(indent) + "}");
            sb.AppendLine();
        }

        private static void WriteStateConstants(StringBuilder sb, AnimatorController controller, int indent)
        {
            var states = GetAllStates(controller);
            if (states.Count == 0)
            {
                sb.AppendLine(Ind(indent) + "// No states found in the controller.");
                return;
            }

            // Generate Enum
            sb.AppendLine(Ind(indent) + "public enum State");
            sb.AppendLine(Ind(indent) + "{");
            foreach (var state in states)
            {
                sb.AppendLine(Ind(indent + 1) + $"{state.name},");
            }

            sb.AppendLine(Ind(indent) + "}");
            sb.AppendLine();

            // Generate Dictionary
            sb.AppendLine(Ind(indent) +
                          "private static readonly Dictionary<State, int> StateHashes = new Dictionary<State, int>");
            sb.AppendLine(Ind(indent) + "{");
            foreach (var state in states)
            {
                sb.AppendLine(Ind(indent + 1) + $"{{ State.{state.name}, Animator.StringToHash(\"{state.name}\") }},");
            }

            sb.AppendLine(Ind(indent) + "};");
            sb.AppendLine();

            // Generate ToHash method
            sb.AppendLine(Ind(indent) + "public static int ToHash(this State state)");
            sb.AppendLine(Ind(indent) + "{");
            sb.AppendLine(Ind(indent + 1) + "return StateHashes[state];");
            sb.AppendLine(Ind(indent) + "}");
        }

        private static List<AnimatorState> GetAllStates(AnimatorController controller)
        {
            var states = new List<AnimatorState>();
            foreach (var layer in controller.layers)
            {
                var stateMachine = layer.stateMachine;
                CollectStatesRecursively(stateMachine, states);
            }

            return states.Distinct().ToList();
        }

        private static void CollectStatesRecursively(AnimatorStateMachine stateMachine, List<AnimatorState> states)
        {
            foreach (var state in stateMachine.states)
            {
                states.Add(state.state);
            }

            foreach (var subMachine in stateMachine.stateMachines)
            {
                CollectStatesRecursively(subMachine.stateMachine, states);
            }
        }

        private static string Ind(int lv) => new string(' ', lv * 4);
    }
}