// Auto-generated by AnimatorBindingGenerator
using UnityEngine;
using System.Collections.Generic;

public static class ControllerBind
{
    public enum Parameter
    {
        Up,
        Down,
        Left,
        Right,
    }

    private static readonly Dictionary<Parameter, int> ParameterHashes = new Dictionary<Parameter, int>
    {
        { Parameter.Up, Animator.StringToHash("Up") },
        { Parameter.Down, Animator.StringToHash("Down") },
        { Parameter.Left, Animator.StringToHash("Left") },
        { Parameter.Right, Animator.StringToHash("Right") },
    };

    public static int ToHash(this Parameter parameter)
    {
        return ParameterHashes[parameter];
    }

    public enum State
    {
        Default,
        LeftUp,
        RightDown,
    }

    private static readonly Dictionary<State, int> StateHashes = new Dictionary<State, int>
    {
        { State.Default, Animator.StringToHash("Default") },
        { State.LeftUp, Animator.StringToHash("LeftUp") },
        { State.RightDown, Animator.StringToHash("RightDown") },
    };

    public static int ToHash(this State state)
    {
        return StateHashes[state];
    }
}
